/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Addresses: () => import('#controllers/addresses_controller'),
  AdminQuotes: () => import('#controllers/admin_quotes_controller'),
  CheckoutSessions: () => import('#controllers/checkout_sessions_controller'),
  EasypostWebhooks: () => import('#controllers/easypost_webhooks_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  NewCustomer: () => import('#controllers/new_customer_controller'),
  Orders: () => import('#controllers/orders_controller'),
  PaypalWebhooks: () => import('#controllers/paypal_webhooks_controller'),
  Profile: () => import('#controllers/profile_controller'),
  ProjectFiles: () => import('#controllers/project_files_controller'),
  Projects: () => import('#controllers/projects_controller'),
  Quotes: () => import('#controllers/quotes_controller'),
  ServiceableCountries: () => import('#controllers/serviceable_countries_controller'),
  StripeWebhooks: () => import('#controllers/stripe_webhooks_controller'),
  VendorAddresses: () => import('#controllers/vendor_addresses_controller'),
  VendorOrders: () => import('#controllers/vendor_orders_controller'),
  VendorShipments: () => import('#controllers/vendor_shipments_controller'),
}
