/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  NewCustomer: () => import('#controllers/new_customer_controller'),
  Profile: () => import('#controllers/profile_controller'),
  ProjectFiles: () => import('#controllers/project_files_controller'),
  Projects: () => import('#controllers/projects_controller'),
  Quotes: () => import('#controllers/quotes_controller'),
}
