/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AddressSchema extends BaseModel {
  static $columns = ['city', 'country', 'createdAt', 'customerId', 'id', 'label', 'line1', 'line2', 'ownerType', 'postalCode', 'state', 'updatedAt', 'vendorId'] as const
  $columns = AddressSchema.$columns
  @column()
  declare city: string
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare customerId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string | null
  @column()
  declare line1: string
  @column()
  declare line2: string | null
  @column()
  declare ownerType: 'customer' | 'vendor'
  @column()
  declare postalCode: string
  @column()
  declare state: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vendorId: number | null
}

export class AuditEventSchema extends BaseModel {
  static $columns = ['createdAt', 'entityId', 'entityType', 'eventType', 'id', 'payload', 'updatedAt', 'userId'] as const
  $columns = AuditEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare entityId: number
  @column()
  declare entityType: string
  @column()
  declare eventType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare payload: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CheckoutSessionSchema extends BaseModel {
  static $columns = ['completedAt', 'createdAt', 'customerId', 'expiredAt', 'expiresAt', 'failedAt', 'id', 'projectId', 'quoteId', 'status', 'updatedAt'] as const
  $columns = CheckoutSessionSchema.$columns
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare customerId: number | null
  @column.dateTime()
  declare expiredAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column.dateTime()
  declare failedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare projectId: number | null
  @column()
  declare quoteId: number | null
  @column()
  declare status: 'active' | 'expired' | 'completed' | 'failed'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CustomerSchema extends BaseModel {
  static $columns = ['companyName', 'createdAt', 'email', 'firstName', 'id', 'lastName', 'paypalCustomerId', 'quickbooksCustomerId', 'stripeCustomerId', 'updatedAt', 'userId', 'uuid'] as const
  $columns = CustomerSchema.$columns
  @column()
  declare companyName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string | null
  @column()
  declare paypalCustomerId: string | null
  @column()
  declare quickbooksCustomerId: string | null
  @column()
  declare stripeCustomerId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare uuid: string
}

export class FdmPricingConfigValueSchema extends BaseModel {
  static $columns = ['bulkFloorBreakGrams', 'bulkFloorLargeMultiplier', 'bulkFloorSigmoidWidthGrams', 'bulkFloorSmallMultiplier', 'createdAt', 'failureBufferMultiplier', 'fixedLineItemCharge', 'id', 'machineRatePerHour', 'modelMaterialRatePerGram', 'oversizeMultiplier', 'oversizeThresholdMm', 'pricingConfigId', 'quantityDecayConstant', 'supportMaterialRatePerGram', 'updatedAt'] as const
  $columns = FdmPricingConfigValueSchema.$columns
  @column()
  declare bulkFloorBreakGrams: string
  @column()
  declare bulkFloorLargeMultiplier: string
  @column()
  declare bulkFloorSigmoidWidthGrams: string
  @column()
  declare bulkFloorSmallMultiplier: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare failureBufferMultiplier: string
  @column()
  declare fixedLineItemCharge: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare machineRatePerHour: string
  @column()
  declare modelMaterialRatePerGram: string
  @column()
  declare oversizeMultiplier: string
  @column()
  declare oversizeThresholdMm: string
  @column()
  declare pricingConfigId: number
  @column()
  declare quantityDecayConstant: string
  @column()
  declare supportMaterialRatePerGram: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FeeSchema extends BaseModel {
  static $columns = ['createdAt', 'defaultAmount', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = FeeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare defaultAmount: string
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MaterialColorSchema extends BaseModel {
  static $columns = ['createdAt', 'hex', 'id', 'isDefault', 'materialId', 'name', 'updatedAt', 'uuid'] as const
  $columns = MaterialColorSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare hex: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean
  @column()
  declare materialId: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
}

export class MaterialSchema extends BaseModel {
  static $columns = ['createdAt', 'densityGPerCm3', 'description', 'id', 'isDefault', 'name', 'technology', 'trueCostPerGram', 'updatedAt', 'uuid'] as const
  $columns = MaterialSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare densityGPerCm3: string | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean
  @column()
  declare name: string
  @column()
  declare technology: 'fdm' | 'sla' | 'sls'
  @column()
  declare trueCostPerGram: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
}

export class OrderFeeSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'feeId', 'id', 'orderId'] as const
  $columns = OrderFeeSchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare feeId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number | null
}

export class OrderItemSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'itemType', 'orderId', 'projectFileId', 'quantity', 'total', 'unitPrice', 'updatedAt'] as const
  $columns = OrderItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemType: string | null
  @column()
  declare orderId: number | null
  @column()
  declare projectFileId: number | null
  @column()
  declare quantity: number
  @column()
  declare total: string
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderStatusHistorySchema extends BaseModel {
  static $columns = ['changedById', 'createdAt', 'id', 'newStatus', 'oldStatus', 'orderId'] as const
  $columns = OrderStatusHistorySchema.$columns
  @column()
  declare changedById: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare newStatus: string
  @column()
  declare oldStatus: string
  @column()
  declare orderId: number | null
}

export class OrderSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'externalReference', 'id', 'orderNumber', 'projectId', 'quoteId', 'status', 'subtotal', 'tax', 'total', 'updatedAt', 'uuid', 'vendorId'] as const
  $columns = OrderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare customerId: number | null
  @column()
  declare externalReference: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderNumber: string
  @column()
  declare projectId: number | null
  @column()
  declare quoteId: number | null
  @column()
  declare status: 'pending' | 'paid' | 'open' | 'accepted' | 'rejected' | 'in_progress' | 'ready_to_ship' | 'shipped' | 'delivered' | 'refunded' | 'cancelled'
  @column()
  declare subtotal: string
  @column()
  declare tax: string
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
  @column()
  declare vendorId: number | null
}

export class PaymentSchema extends BaseModel {
  static $columns = ['amount', 'authorizedAt', 'cancelledAt', 'capturedAt', 'checkoutSessionId', 'createdAt', 'failedAt', 'id', 'netAmount', 'provider', 'providerFee', 'refundedAt', 'status', 'transactionId', 'updatedAt'] as const
  $columns = PaymentSchema.$columns
  @column()
  declare amount: string
  @column.dateTime()
  declare authorizedAt: DateTime | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column.dateTime()
  declare capturedAt: DateTime | null
  @column()
  declare checkoutSessionId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare failedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare netAmount: string
  @column()
  declare provider: string | null
  @column()
  declare providerFee: string
  @column.dateTime()
  declare refundedAt: DateTime | null
  @column()
  declare status: 'pending' | 'authorized' | 'captured' | 'failed' | 'refunded' | 'cancelled'
  @column()
  declare transactionId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PricingConfigSchema extends BaseModel {
  static $columns = ['activatedAt', 'createdAt', 'createdById', 'id', 'isActive', 'name', 'notes', 'technology', 'updatedAt', 'version'] as const
  $columns = PricingConfigSchema.$columns
  @column.dateTime()
  declare activatedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdById: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare technology: 'fdm'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class ProjectFileSliceVariantSchema extends BaseModel {
  static $columns = ['createdAt', 'filamentUsedGrams', 'gcodeStorageKey', 'id', 'infill', 'layerHeight', 'printTimeEstimatedSeconds', 'projectFileId', 'updatedAt', 'variant'] as const
  $columns = ProjectFileSliceVariantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare filamentUsedGrams: number
  @column()
  declare gcodeStorageKey: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare infill: number | null
  @column()
  declare layerHeight: number
  @column()
  declare printTimeEstimatedSeconds: number
  @column()
  declare projectFileId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare variant: 'baseline' | 'infill_probe' | 'layer_height_probe' | 'support_probe'
}

export class ProjectFileSchema extends BaseModel {
  static $columns = ['colorId', 'createdAt', 'fileSize', 'fileStorageKey', 'gcodeStorageKey', 'id', 'infill', 'layerHeight', 'materialId', 'mimeType', 'modelMaterialGrams', 'originalName', 'printTimeEstimatedSeconds', 'projectId', 'status', 'supportMaterialGrams', 'surfaceAreaMm2', 'technology', 'updatedAt', 'uuid', 'volume', 'x', 'y', 'z'] as const
  $columns = ProjectFileSchema.$columns
  @column()
  declare colorId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare fileSize: bigint | number
  @column()
  declare fileStorageKey: string
  @column()
  declare gcodeStorageKey: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare infill: number | null
  @column()
  declare layerHeight: number | null
  @column()
  declare materialId: number | null
  @column()
  declare mimeType: string
  @column()
  declare modelMaterialGrams: number | null
  @column()
  declare originalName: string
  @column()
  declare printTimeEstimatedSeconds: number | null
  @column()
  declare projectId: number | null
  @column()
  declare status: 'pending' | 'processing' | 'completed' | 'failed'
  @column()
  declare supportMaterialGrams: number | null
  @column()
  declare surfaceAreaMm2: number | null
  @column()
  declare technology: 'fdm' | 'sla' | 'sls'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
  @column()
  declare volume: number | null
  @column()
  declare x: number | null
  @column()
  declare y: number | null
  @column()
  declare z: number | null
}

export class ProjectSchema extends BaseModel {
  static $columns = ['cancelledAt', 'createdAt', 'customerId', 'description', 'expiredAt', 'fulfilledAt', 'id', 'metadata', 'source', 'status', 'title', 'updatedAt', 'uuid'] as const
  $columns = ProjectSchema.$columns
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare customerId: number | null
  @column()
  declare description: string | null
  @column.dateTime()
  declare expiredAt: DateTime | null
  @column.dateTime()
  declare fulfilledAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any | null
  @column()
  declare source: 'instant_quote' | 'manual'
  @column()
  declare status: 'draft' | 'quoted' | 'awaiting_checkout' | 'ordered' | 'fulfilled' | 'cancelled' | 'expired'
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
}

export class QueueJobSchema extends BaseModel {
  static $columns = ['acquiredAt', 'data', 'dedupAt', 'dedupId', 'dedupTtl', 'error', 'executeAt', 'finishedAt', 'id', 'queue', 'score', 'status', 'workerId'] as const
  $columns = QueueJobSchema.$columns
  @column()
  declare acquiredAt: bigint | number | null
  @column()
  declare data: string
  @column()
  declare dedupAt: bigint | number | null
  @column()
  declare dedupId: string | null
  @column()
  declare dedupTtl: bigint | number | null
  @column()
  declare error: string | null
  @column()
  declare executeAt: bigint | number | null
  @column()
  declare finishedAt: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queue: string
  @column()
  declare score: bigint | number | null
  @column()
  declare status: string
  @column()
  declare workerId: string | null
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = ['createdAt', 'cronExpression', 'everyMs', 'fromDate', 'id', 'lastRunAt', 'name', 'nextRunAt', 'payload', 'runCount', 'runLimit', 'status', 'timezone', 'toDate'] as const
  $columns = QueueScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cronExpression: string | null
  @column()
  declare everyMs: bigint | number | null
  @column.dateTime()
  declare fromDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column()
  declare payload: string
  @column()
  declare runCount: number
  @column()
  declare runLimit: number | null
  @column()
  declare status: string
  @column()
  declare timezone: string
  @column.dateTime()
  declare toDate: DateTime | null
}

export class QuoteFeeSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'feeId', 'id', 'quoteId'] as const
  $columns = QuoteFeeSchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare feeId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare quoteId: number | null
}

export class QuoteItemSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'itemType', 'pricingConfigId', 'pricingSnapshot', 'projectFileId', 'quantity', 'quoteId', 'total', 'unitPrice', 'updatedAt'] as const
  $columns = QuoteItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemType: string | null
  @column()
  declare pricingConfigId: number | null
  @column()
  declare pricingSnapshot: any | null
  @column()
  declare projectFileId: number | null
  @column()
  declare quantity: number
  @column()
  declare quoteId: number | null
  @column()
  declare total: string
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class QuoteSchema extends BaseModel {
  static $columns = ['createdAt', 'createdById', 'generatedBy', 'id', 'notes', 'projectId', 'rejectedAt', 'rejectionReason', 'revision', 'status', 'subtotal', 'tax', 'total', 'updatedAt', 'uuid'] as const
  $columns = QuoteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdById: number | null
  @column()
  declare generatedBy: 'system' | 'user'
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare projectId: number | null
  @column.dateTime()
  declare rejectedAt: DateTime | null
  @column()
  declare rejectionReason: 'abandoned' | 'declined' | null
  @column()
  declare revision: number
  @column()
  declare status: 'draft' | 'sent' | 'accepted' | 'rejected'
  @column()
  declare subtotal: string
  @column()
  declare tax: string
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RefundSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'id', 'paymentId', 'reason', 'updatedAt'] as const
  $columns = RefundSchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare paymentId: number | null
  @column()
  declare reason: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SessionSchema extends BaseModel {
  static $columns = ['data', 'expiresAt', 'id', 'userId'] as const
  $columns = SessionSchema.$columns
  @column()
  declare data: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
}

export class ShipmentSchema extends BaseModel {
  static $columns = ['addressId', 'cancelledAt', 'carrier', 'createdAt', 'deliveredAt', 'id', 'inTransitAt', 'labelCreatedAt', 'orderId', 'serviceLevel', 'shippedAt', 'status', 'trackingNumber', 'updatedAt', 'vendorId'] as const
  $columns = ShipmentSchema.$columns
  @column()
  declare addressId: number | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare carrier: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare inTransitAt: DateTime | null
  @column.dateTime()
  declare labelCreatedAt: DateTime | null
  @column()
  declare orderId: number | null
  @column()
  declare serviceLevel: string | null
  @column.dateTime()
  declare shippedAt: DateTime | null
  @column()
  declare status: 'pending' | 'label_created' | 'shipped' | 'in_transit' | 'delivered' | 'cancelled'
  @column()
  declare trackingNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vendorId: number | null
}

export class ShippingLabelSchema extends BaseModel {
  static $columns = ['cost', 'createdAt', 'id', 'labelPdfUrl', 'labelUrl', 'provider', 'shipmentId', 'updatedAt', 'voidedAt'] as const
  $columns = ShippingLabelSchema.$columns
  @column()
  declare cost: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare labelPdfUrl: string | null
  @column()
  declare labelUrl: string | null
  @column()
  declare provider: string
  @column()
  declare shipmentId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare voidedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt', 'uuid'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: 'admin' | 'customer' | 'vendor'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
}

export class VendorPayoutRateSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'materialId', 'percentage', 'updatedAt', 'vendorId'] as const
  $columns = VendorPayoutRateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare materialId: number | null
  @column()
  declare percentage: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vendorId: number | null
}

export class VendorPayoutSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'id', 'orderId', 'paidAt', 'provider', 'providerTransactionId', 'status', 'updatedAt', 'vendorId'] as const
  $columns = VendorPayoutSchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number | null
  @column.dateTime()
  declare paidAt: DateTime | null
  @column()
  declare provider: string
  @column()
  declare providerTransactionId: string | null
  @column()
  declare status: 'pending' | 'paid' | 'failed' | 'processing'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vendorId: number | null
}

export class VendorSchema extends BaseModel {
  static $columns = ['createdAt', 'displayName', 'id', 'paypalAccountId', 'quickbooksVendorId', 'stripeAccountId', 'taxStatus', 'updatedAt', 'userId', 'uuid'] as const
  $columns = VendorSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare displayName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare paypalAccountId: string | null
  @column()
  declare quickbooksVendorId: string | null
  @column()
  declare stripeAccountId: string | null
  @column()
  declare taxStatus: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare uuid: string
}
