/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type AddressTransformer from '#transformers/address_transformer'
import type AdminQuoteReviewTransformer from '#transformers/admin_quote_review_transformer'
import type CheckoutSessionTransformer from '#transformers/checkout_session_transformer'
import type CustomerTransformer from '#transformers/customer_transformer'
import type InstantQuoteFileTransformer from '#transformers/instant_quote_file_transformer'
import type OrderTransformer from '#transformers/order_transformer'
import type ProjectFileTransformer from '#transformers/project_file_transformer'
import type QuoteTransformer from '#transformers/quote_transformer'
import type ServiceableCountryTransformer from '#transformers/serviceable_country_transformer'
import type ShipmentTransformer from '#transformers/shipment_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type VendorPayoutMethodTransformer from '#transformers/vendor_payout_method_transformer'
import type VendorPayoutRateTransformer from '#transformers/vendor_payout_rate_transformer'
import type VendorPayoutTransformer from '#transformers/vendor_payout_transformer'
import type VendorShipmentTransformer from '#transformers/vendor_shipment_transformer'

export namespace Data {
  export type Address = InferData<AddressTransformer>
  export namespace Address {
    export type Variants = InferVariants<AddressTransformer>
  }
  export type AdminQuoteReview = InferData<AdminQuoteReviewTransformer>
  export namespace AdminQuoteReview {
    export type Variants = InferVariants<AdminQuoteReviewTransformer>
  }
  export type CheckoutSession = InferData<CheckoutSessionTransformer>
  export namespace CheckoutSession {
    export type Variants = InferVariants<CheckoutSessionTransformer>
  }
  export type Customer = InferData<CustomerTransformer>
  export namespace Customer {
    export type Variants = InferVariants<CustomerTransformer>
  }
  export type InstantQuoteFile = InferData<InstantQuoteFileTransformer>
  export namespace InstantQuoteFile {
    export type Variants = InferVariants<InstantQuoteFileTransformer>
  }
  export type Order = InferData<OrderTransformer>
  export namespace Order {
    export type Variants = InferVariants<OrderTransformer>
  }
  export type ProjectFile = InferData<ProjectFileTransformer>
  export namespace ProjectFile {
    export type Variants = InferVariants<ProjectFileTransformer>
  }
  export type Quote = InferData<QuoteTransformer>
  export namespace Quote {
    export type Variants = InferVariants<QuoteTransformer>
  }
  export type ServiceableCountry = InferData<ServiceableCountryTransformer>
  export namespace ServiceableCountry {
    export type Variants = InferVariants<ServiceableCountryTransformer>
  }
  export type Shipment = InferData<ShipmentTransformer>
  export namespace Shipment {
    export type Variants = InferVariants<ShipmentTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type VendorPayoutMethod = InferData<VendorPayoutMethodTransformer>
  export namespace VendorPayoutMethod {
    export type Variants = InferVariants<VendorPayoutMethodTransformer>
  }
  export type VendorPayoutRate = InferData<VendorPayoutRateTransformer>
  export namespace VendorPayoutRate {
    export type Variants = InferVariants<VendorPayoutRateTransformer>
  }
  export type VendorPayout = InferData<VendorPayoutTransformer>
  export namespace VendorPayout {
    export type Variants = InferVariants<VendorPayoutTransformer>
  }
  export type VendorShipment = InferData<VendorShipmentTransformer>
  export namespace VendorShipment {
    export type Variants = InferVariants<VendorShipmentTransformer>
  }
}
